START TRANSACTION;
ALTER TABLE public.retenciones_reglas ADD "ConceptoRetencionId" integer;

ALTER TABLE public.productos ADD concepto_retencion_id integer;

CREATE TABLE public.conceptos_retencion (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "CodigoDian" character varying(10),
    "PorcentajeSugerido" numeric(5,2),
    "Activo" boolean NOT NULL DEFAULT TRUE,
    "CreadoPor" text NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "ModificadoPor" text,
    "FechaModificacion" timestamp with time zone,
    CONSTRAINT "PK_conceptos_retencion" PRIMARY KEY ("Id")
);

INSERT INTO public.conceptos_retencion ("Id", "Activo", "CodigoDian", "CreadoPor", "FechaCreacion", "FechaModificacion", "ModificadoPor", "Nombre", "PorcentajeSugerido")
VALUES (1, TRUE, '2307', '', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, NULL, 'Compras generales', 2.5);
INSERT INTO public.conceptos_retencion ("Id", "Activo", "CodigoDian", "CreadoPor", "FechaCreacion", "FechaModificacion", "ModificadoPor", "Nombre", "PorcentajeSugerido")
VALUES (2, TRUE, '2304', '', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, NULL, 'Servicios generales', 4.0);
INSERT INTO public.conceptos_retencion ("Id", "Activo", "CodigoDian", "CreadoPor", "FechaCreacion", "FechaModificacion", "ModificadoPor", "Nombre", "PorcentajeSugerido")
VALUES (3, TRUE, '2301', '', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, NULL, 'Honorarios', 11.0);
INSERT INTO public.conceptos_retencion ("Id", "Activo", "CodigoDian", "CreadoPor", "FechaCreacion", "FechaModificacion", "ModificadoPor", "Nombre", "PorcentajeSugerido")
VALUES (4, TRUE, '2302', '', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, NULL, 'Comisiones', 11.0);
INSERT INTO public.conceptos_retencion ("Id", "Activo", "CodigoDian", "CreadoPor", "FechaCreacion", "FechaModificacion", "ModificadoPor", "Nombre", "PorcentajeSugerido")
VALUES (5, TRUE, '2306', '', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, NULL, 'Arrendamientos', 3.5);

UPDATE public.retenciones_reglas SET "ConceptoRetencionId" = NULL
WHERE "Id" = 1;

UPDATE public.retenciones_reglas SET "ConceptoRetencionId" = NULL
WHERE "Id" = 2;

UPDATE public.retenciones_reglas SET "ConceptoRetencionId" = NULL
WHERE "Id" = 3;

CREATE INDEX "IX_retenciones_reglas_ConceptoRetencionId" ON public.retenciones_reglas ("ConceptoRetencionId");

CREATE INDEX "IX_productos_concepto_retencion_id" ON public.productos (concepto_retencion_id);

ALTER TABLE public.productos ADD CONSTRAINT "FK_productos_conceptos_retencion_concepto_retencion_id" FOREIGN KEY (concepto_retencion_id) REFERENCES public.conceptos_retencion ("Id") ON DELETE SET NULL;

ALTER TABLE public.retenciones_reglas ADD CONSTRAINT "FK_retenciones_reglas_conceptos_retencion_ConceptoRetencionId" FOREIGN KEY ("ConceptoRetencionId") REFERENCES public.conceptos_retencion ("Id") ON DELETE SET NULL;

SELECT setval(
    pg_get_serial_sequence('public.conceptos_retencion', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM public.conceptos_retencion) + 1,
        nextval(pg_get_serial_sequence('public.conceptos_retencion', 'Id'))),
    false);

INSERT INTO public.__ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260309183242_AgregarConceptoRetencion', '9.0.1');

COMMIT;

